# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.__version__)
print(np.show_config)

1.20.3
<function show at 0x0000017A8A5CB700>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
arr = np.zeros

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [6]:
x = np.array([1,2,3])
print(x.size * x.itemsize)

12


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [7]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [8]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [10]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [11]:
x = np.array([1,2,3])
print(x[::-1])

[3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [13]:
print(np.arange(9).reshape((3, 3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [14]:
a = np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [16]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [21]:
print(np.random.random((3,3,3)))

[[[0.76177422 0.70251585 0.0579892 ]
  [0.78607261 0.63400222 0.31250479]
  [0.02846298 0.88288754 0.53121701]]

 [[0.68530186 0.81633829 0.81166552]
  [0.65062126 0.15636395 0.78778672]
  [0.38721114 0.8728699  0.32028049]]

 [[0.11013457 0.58272774 0.55806538]
  [0.98940148 0.50473947 0.48856213]
  [0.86657165 0.34608386 0.35037056]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [22]:
a = np.random.random((10,10))
print(a.min())
print(a.max())

0.008792005087638444
0.9953748789822475


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [24]:
a = np.random.random(30)
print(a.mean())

0.41250914365628444


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [27]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [3]:
import numpy as np
x= np.ones((3,3))
y= np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(y)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [5]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [6]:
a = np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [10]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [3]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x = np.zeros((8,8),dtype=int)


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [4]:
a = np.random.random((5,5))
max_, min_ = a.max(), a.min()
a = (a - min_)/(max_ - min_)
print(a)

[[0.57106827 0.3596728  0.         0.21590554 0.87641427]
 [0.5632251  0.15884875 1.         0.40243291 0.75721931]
 [0.08950237 0.37882618 0.14000217 0.29794532 0.73353406]
 [0.5969689  0.49866477 0.76271122 0.78897393 0.62713702]
 [0.24031232 0.1356148  0.06927397 0.57889172 0.31136097]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [6]:
colors = np.dtype([("R", np.ubyte, 1),
                  ("G", np.ubyte, 1),
                  ("B", np.ubyte, 1),
                  ("A", np.ubyte, 1)])

C:\Users\gladi\AppData\Local\Temp/ipykernel_27916/3865552975.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  colors = np.dtype([("R", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [7]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [8]:
a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [9]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [12]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [13]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\gladi\AppData\Local\Temp/ipykernel_27916/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\gladi\AppData\Local\Temp/ipykernel_27916/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [14]:
a = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(a)), a))

[  7.  -7. -10.   4.  -7.   9.  -6.  -6.  -6.   9.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [16]:
a = np.random.randint(0,2,2)
b = np.random.randint(0,2,2)
print(np.intersect1d(a,b))

[0]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [18]:
np.seterr(all="ignore")
print(np.ones(1) / 0)

[inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [19]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
#False

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [22]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
today     = np.datetime64('today', 'D')
print(today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2022-04-10
2022-04-11
2022-04-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [23]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [24]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
print(np.multiply(A,B,out=A))

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [29]:
a = np.random.uniform(0,5,5)

print (a - a%1)
print (np.floor(a))
print (np.ceil(a)-1)
print (a.astype(int))
print (np.trunc(a))

[4. 1. 2. 2. 1.]
[4. 1. 2. 2. 1.]
[4. 1. 2. 2. 1.]
[4 1 2 2 1]
[4. 1. 2. 2. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [30]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [32]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [33]:
print(np.linspace(0,1,11,endpoint=False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [37]:
a = np.random.random(10)
a.sort()
print(a)

[0.23866076 0.41613959 0.41989513 0.46374795 0.48342104 0.51556889
 0.83210979 0.92238484 0.95938879 0.98549498]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [38]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [39]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [40]:
a= np.ones(10)
a.flags.writeable = False
a[0] = 14

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [41]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.99776633 0.41454804 0.43404137 0.99279985 0.75464797 0.8939718
 1.17832731 0.86469293 0.75778324 0.36670203]
[1.52862582 0.07054376 0.70518435 0.01107005 0.41561071 1.25074614
 0.62633229 1.24867843 1.51635249 1.03027935]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [42]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.83415161 0.15564523 0.2367578  0.26464647 0.         0.50052664
 0.10685515 0.66896611 0.04085068 0.76097117]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [46]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [50]:
x = np.arange(5)
y = x+.5
c = 1/np.subtract.outer(x,y)

print(c)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [51]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [55]:
print(np.zeros((16,16)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [56]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

85


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [58]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\gladi\AppData\Local\Temp/ipykernel_27916/274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [64]:
a = np.random.random((10,2))

b,c = np.atleast_2d(a[:,0],a[:,1])
print(b)
print(c)
d = np.sqrt((b-b.T)**2+(c-c.T)**2)
print(d)

[[0.83188375 0.89386101 0.65494288 0.08567801 0.54136349 0.01511756
  0.3870219  0.75026793 0.06519966 0.69358952]]
[[0.15005098 0.2885174  0.54651355 0.14671579 0.9794739  0.23974572
  0.07037334 0.91089474 0.42929083 0.04956915]]
[[0.         0.15170409 0.43415509 0.74621319 0.87883127 0.82167644
  0.45194091 0.76520871 0.81595306 0.17094412]
 [0.15170409 0.         0.35163033 0.82052876 0.77567737 0.88009587
  0.55179046 0.63872727 0.84053363 0.31177706]
 [0.43415509 0.35163033 0.         0.69562975 0.44761026 0.70956533
  0.54634344 0.37664374 0.6012805  0.49844488]
 [0.74621319 0.82052876 0.69562975 0.         0.94928148 0.11676192
  0.31086381 1.01274341 0.28331611 0.61562478]
 [0.87883127 0.77567737 0.44761026 0.94928148 0.         0.90781748
  0.92210908 0.21987307 0.72762174 0.94228213]
 [0.82167644 0.88009587 0.70956533 0.11676192 0.90781748 0.
  0.40865615 0.99543311 0.19604991 0.70462141]
 [0.45194091 0.55179046 0.54634344 0.31086381 0.92210908 0.40865615
  0.         0.915

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [68]:
a = np.arange(10, dtype=np.float32)
a = a.astype(np.int32,copy = False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [69]:
from io import StringIO

string = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
a = np.genfromtxt(string, delimiter=",", dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\gladi\AppData\Local\Temp/ipykernel_27916/3854551515.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.genfromtxt(string, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [70]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [72]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [76]:
p = 3
Z = np.zeros((10,10))
np.put(Z, np.random.choice(range(10*10), p, replace=False),p)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [77]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 1.61864851e-01 -4.01985274e-02  2.87205002e-01 -3.68634751e-02
   4.24040805e-05  1.47789230e-01 -1.02214483e-01  8.45215087e-02
  -2.03337013e-01 -2.98809497e-01]
 [-4.09300076e-01  4.64952945e-01 -3.08289379e-01  4.03572386e-02
   3.91320383e-01 -3.14217027e-03 -5.47989571e-02 -1.90012689e-01
   4.86104272e-01 -4.17191568e-01]
 [-9.77803376e-02 -5.67466580e-02 -4.43113083e-01  1.50214760e-01
   3.77636708e-01 -1.95908660e-01  3.22027394e-01  5.78113033e-02
   7.40352394e-02 -1.88176667e-01]
 [ 2.64651775e-02 -2.85215330e-01  2.67702980e-01  1.03734045e-01
  -9.66947595e-02  3.58868334e-01 -4.53151660e-01  4.59263113e-01
  -2.31158933e-01 -1.49812966e-01]
 [-3.10997277e-01 -1.98784654e-02 -4.15459315e-01  3.75477153e-01
  -4.30651219e-01  1.55066892e-01  3.63295435e-01 -3.66377561e-01
   5.09281141e-01  1.40243217e-01]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [78]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 0 7]
 [4 1 0]
 [5 8 1]]
[[8 0 7]
 [4 1 0]
 [5 8 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [80]:
X = np.random.rand(5, 10)
print((~X.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [81]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4703216446178473


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [84]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [85]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [86]:

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[4. 2. 3. 4. 4. 3. 1. 1. 5. 3.]
[7. 3. 5. 7. 7. 5. 1. 1. 9. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [87]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [88]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [89]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[47 68 76 74]
 [51 57 58 65]
 [47 70 51 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [91]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.45719444 0.6020465  0.48914929 0.51146598 0.57982334 0.47022903
 0.46036876 0.51341167 0.2738567  0.20057434]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [92]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([0.60855829, 1.09894514, 1.62585108, 0.48374549, 1.30410295])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [93]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [2]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [3]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [4]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(15, 43) (15, 77) (20, 24) (20, 61) (23, 40) (23, 47) (23, 66) (23, 90)
 (24, 61) (25, 48) (25, 71) (35, 38) (35, 59) (38, 59) (40, 47) (43, 77)
 (45, 49) (45, 68) (45, 84) (45, 92) (48, 71) (49, 92) (51, 91) (51, 98)
 (56, 75) (56, 96) (66, 90) (68, 84) (75, 96) (91, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [5]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [6]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [7]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [8]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.23948071, -0.63491898,  0.42926458,  0.19841644, -0.80810212,
        0.27358435, -0.08034585, -0.92312602,  0.50227527, -0.96122495,
        0.09100537, -0.14080776, -0.04634129,  0.77328305, -0.29286713,
       -0.26271349,  0.39178152,  0.68218519, -0.54993353,  0.43593323,
        0.23904233, -0.55858312,  0.45817729,  0.6425207 ,  0.25943724,
        0.50639557, -0.67657858,  0.15091503, -0.26964449,  0.21837324,
        0.71940291, -0.08226858,  0.88059759,  0.80530698, -0.87248175,
        0.49582672, -0.84361019,  0.2963797 , -0.07998181,  0.36351464,
        0.81541456,  0.60073367,  0.66271526,  0.13285714,  0.34696747,
        0.70439488, -0.80945808, -0.84285488,  0.20025929, -0.45020803,
        0.27025864, -0.58345459,  0.3081274 , -0.80273202, -0.99003888,
       -0.32624475,  0.90780856,  0.76793037, -0.39065485,  0.01301017,
        0.60051776,  0.30047277,  0.61047666,  0.26592483, -0.82383151,
       -0.16808445,  0.23484019,  0.97233947,  0.47425415, -0.42

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [9]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.67775691 15.32258759  7.12332602  8.38087365 10.34542144  1.14371334
  1.98885505 10.34982958  4.95470133 10.52463375]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [10]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 9.28433641  5.47688425  4.92360618  1.43386443  7.67900998  7.61138199
   0.41224152  0.85999989  6.9329773   3.26626184]
 [ 0.15846881  9.27107053  0.10212455 14.1469442   7.46060814  7.94317419
  15.15821332  6.19870605  1.54400857 11.06318453]
 [ 8.46920746  0.72730648  0.36904447  7.67688574  1.59155487  2.29296043
   4.96327437  5.56395542  6.43331396  0.64199278]
 [ 7.90431673 10.40144187  7.32275281 17.62053165  7.83482165  5.71392899
  13.07096088 13.47277714  6.37024844  6.24107835]
 [ 6.91366142  5.7511527   7.1355485   0.44567307  7.72407634  6.87146558
   0.28503368  1.30427317  4.51453704  1.75186254]
 [ 6.31600866  0.76531973  2.13577888  7.07942872  1.35427963  1.39007444
   5.83070192  3.84658033  4.25186109  2.1718909 ]
 [ 1.53751394  3.71808767  3.63604778  8.75140242  1.95164822  2.91986708
  10.09463069  2.51642352  0.43819045  7.10985061]
 [10.1780401   6.74790813  5.24957274  0.36993802  8.99376868  8.99535451
   1.79579718  0.48703969  7.77226489  4.57637357]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [11]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 9 4 8 2 8 2 8 6 3]
 [4 6 7 0 7 9 6 4 7 5]
 [2 5 0 8 1 1 0 8 5 5]
 [2 8 4 1 3 7 9 6 9 0]
 [2 5 6 6 0 9 3 4 3 7]
 [3 9 9 9 1 9 0 6 3 5]
 [2 6 5 8 5 2 2 9 0 3]
 [0 4 2 2 6 2 7 3 3 8]
 [3 8 4 7 4 0 8 3 0 7]
 [1 3 3 3 0 1 3 7 1 4]]
[[0 0 0 0 0]
 [0 8 9 4 8]
 [0 4 6 7 0]
 [0 2 5 0 8]
 [0 2 8 4 1]]


C:\Users\gladi\AppData\Local\Temp/ipykernel_21228/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [12]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [13]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [14]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [15]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 3]
   [0 4 2]
   [1 3 2]]

  [[0 3 2]
   [4 2 2]
   [3 2 3]]

  [[3 2 0]
   [2 2 0]
   [2 3 2]]

  [[2 0 0]
   [2 0 2]
   [3 2 0]]

  [[0 0 4]
   [0 2 1]
   [2 0 4]]

  [[0 4 3]
   [2 1 1]
   [0 4 4]]

  [[4 3 1]
   [1 1 0]
   [4 4 2]]

  [[3 1 0]
   [1 0 4]
   [4 2 4]]]


 [[[0 4 2]
   [1 3 2]
   [0 1 0]]

  [[4 2 2]
   [3 2 3]
   [1 0 2]]

  [[2 2 0]
   [2 3 2]
   [0 2 1]]

  [[2 0 2]
   [3 2 0]
   [2 1 4]]

  [[0 2 1]
   [2 0 4]
   [1 4 0]]

  [[2 1 1]
   [0 4 4]
   [4 0 4]]

  [[1 1 0]
   [4 4 2]
   [0 4 0]]

  [[1 0 4]
   [4 2 4]
   [4 0 4]]]


 [[[1 3 2]
   [0 1 0]
   [0 3 2]]

  [[3 2 3]
   [1 0 2]
   [3 2 3]]

  [[2 3 2]
   [0 2 1]
   [2 3 2]]

  [[3 2 0]
   [2 1 4]
   [3 2 2]]

  [[2 0 4]
   [1 4 0]
   [2 2 2]]

  [[0 4 4]
   [4 0 4]
   [2 2 3]]

  [[4 4 2]
   [0 4 0]
   [2 3 3]]

  [[4 2 4]
   [4 0 4]
   [3 3 2]]]


 [[[0 1 0]
   [0 3 2]
   [2 0 4]]

  [[1 0 2]
   [3 2 3]
   [0 4 2]]

  [[0 2 1]
   [2 3 2]
   [4 2 4]]

  [[2 1 4]
   [3 2 2]
   [2 4 1]]

  [[1 4 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [16]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 13  9 14  8]
 [13  0 13 15  2]
 [ 9 13  2 42  6]
 [14 15 42  3 10]
 [ 8  2  6 10  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [17]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [18]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [19]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [20]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [21]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [22]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [24]:
x = np.random.rand(5)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.1 µs ± 21.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
744 ns ± 12.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2.61 µs ± 91.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [25]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [26]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[0 3 2]
 [2 1 0]
 [1 0 0]
 [1 2 0]
 [0 1 3]
 [4 4 0]
 [1 4 2]
 [3 0 4]
 [3 0 0]
 [0 4 2]]
[[0 3 2]
 [2 1 0]
 [1 0 0]
 [1 2 0]
 [0 1 3]
 [4 4 0]
 [1 4 2]
 [3 0 4]
 [3 0 0]
 [0 4 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [27]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [28]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [29]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.01178338, 0.07196316, 0.15401222, 0.48779734, 0.52242892,
        0.03478193, 0.45366987, 0.04348001, 0.25085039, 0.16185114],
       [0.0069285 , 0.04231356, 0.09055752, 0.28681954, 0.30718254,
        0.0204514 , 0.26675296, 0.02556577, 0.14749731, 0.09516671],
       [0.01108992, 0.06772804, 0.14494841, 0.45908985, 0.49168332,
        0.03273497, 0.42697083, 0.04092115, 0.23608753, 0.152326  ],
       [0.00118028, 0.0072082 , 0.01542666, 0.04886029, 0.05232917,
        0.00348394, 0.04544191, 0.00435518, 0.02512647, 0.01621184],
       [0.00814091, 0.04971795, 0.10640406, 0.33700972, 0.36093601,
        0.02403016, 0.31343172, 0.03003949, 0.17330767, 0.11181981],
       [0.01921925, 0.1173753 , 0.25120116, 0.79562035, 0.85210609,
        0.05673096, 0.73995686, 0.07091793, 0.40914877, 0.2639868 ],
       [0.02078338, 0.1269277 , 0.27164477, 0.86037065, 0.92145339,
        0.06134792, 0.80017707, 0.07668947, 0.44244669, 0.28547095],
       [0.00335997, 0.0205199 , 0.0439157

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [31]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
print(x_int)
print(y_int)

[ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  5.28038

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [32]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [33]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.15804476  0.21708095]
